// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/deploy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	DeploymentData []byte                 `protobuf:"bytes,2,opt,name=deployment_data,json=deploymentData,proto3" json:"deployment_data,omitempty"`
	Filename       string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	UseYaml        bool                   `protobuf:"varint,4,opt,name=use_yaml,json=useYaml,proto3" json:"use_yaml,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_proto_deploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeployRequest) GetDeploymentData() []byte {
	if x != nil {
		return x.DeploymentData
	}
	return nil
}

func (x *DeployRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DeployRequest) GetUseYaml() bool {
	if x != nil {
		return x.UseYaml
	}
	return false
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_proto_deploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_proto_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *DeployResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type ExecutionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	JobName       string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	StepName      string                 `protobuf:"bytes,3,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	LogType       string                 `protobuf:"bytes,4,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"` // "info", "error", "stdout", "stderr"
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Completed     bool                   `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLog) Reset() {
	*x = ExecutionLog{}
	mi := &file_proto_deploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLog) ProtoMessage() {}

func (x *ExecutionLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLog.ProtoReflect.Descriptor instead.
func (*ExecutionLog) Descriptor() ([]byte, []int) {
	return file_proto_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ExecutionLog) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ExecutionLog) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecutionLog) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *ExecutionLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionLog) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_deploy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_deploy_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StatusRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_deploy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_proto_deploy_proto protoreflect.FileDescriptor

const file_proto_deploy_proto_rawDesc = "" +
	"\n" +
	"\x12proto/deploy.proto\x12\x06deploy\"\x88\x01\n" +
	"\rDeployRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12'\n" +
	"\x0fdeployment_data\x18\x02 \x01(\fR\x0edeploymentData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x19\n" +
	"\buse_yaml\x18\x04 \x01(\bR\auseYaml\"i\n" +
	"\x0eDeployResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\"\xb7\x01\n" +
	"\fExecutionLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12\x1b\n" +
	"\tstep_name\x18\x03 \x01(\tR\bstepName\x12\x19\n" +
	"\blog_type\x18\x04 \x01(\tR\alogType\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\bR\tcompleted\"M\n" +
	"\rStatusRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"`\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted2\xd1\x01\n" +
	"\x11DeploymentService\x127\n" +
	"\x06Deploy\x12\x15.deploy.DeployRequest\x1a\x16.deploy.DeployResponse\x12=\n" +
	"\fDeployStream\x12\x15.deploy.DeployRequest\x1a\x14.deploy.ExecutionLog0\x01\x12D\n" +
	"\x13GetDeploymentStatus\x12\x15.deploy.StatusRequest\x1a\x16.deploy.StatusResponseB4Z2github.com/ten-james/go-deploy-system/shared/protob\x06proto3"

var (
	file_proto_deploy_proto_rawDescOnce sync.Once
	file_proto_deploy_proto_rawDescData []byte
)

func file_proto_deploy_proto_rawDescGZIP() []byte {
	file_proto_deploy_proto_rawDescOnce.Do(func() {
		file_proto_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deploy_proto_rawDesc), len(file_proto_deploy_proto_rawDesc)))
	})
	return file_proto_deploy_proto_rawDescData
}

var file_proto_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_deploy_proto_goTypes = []any{
	(*DeployRequest)(nil),  // 0: deploy.DeployRequest
	(*DeployResponse)(nil), // 1: deploy.DeployResponse
	(*ExecutionLog)(nil),   // 2: deploy.ExecutionLog
	(*StatusRequest)(nil),  // 3: deploy.StatusRequest
	(*StatusResponse)(nil), // 4: deploy.StatusResponse
}
var file_proto_deploy_proto_depIdxs = []int32{
	0, // 0: deploy.DeploymentService.Deploy:input_type -> deploy.DeployRequest
	0, // 1: deploy.DeploymentService.DeployStream:input_type -> deploy.DeployRequest
	3, // 2: deploy.DeploymentService.GetDeploymentStatus:input_type -> deploy.StatusRequest
	1, // 3: deploy.DeploymentService.Deploy:output_type -> deploy.DeployResponse
	2, // 4: deploy.DeploymentService.DeployStream:output_type -> deploy.ExecutionLog
	4, // 5: deploy.DeploymentService.GetDeploymentStatus:output_type -> deploy.StatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_deploy_proto_init() }
func file_proto_deploy_proto_init() {
	if File_proto_deploy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deploy_proto_rawDesc), len(file_proto_deploy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deploy_proto_goTypes,
		DependencyIndexes: file_proto_deploy_proto_depIdxs,
		MessageInfos:      file_proto_deploy_proto_msgTypes,
	}.Build()
	File_proto_deploy_proto = out.File
	file_proto_deploy_proto_goTypes = nil
	file_proto_deploy_proto_depIdxs = nil
}
